---
title: "Weight of Fish"
author: "Aeilani Felix"
date: "Spring 2024"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

# Predicting Fish Weight
We will find the best model by using two variables to predict the weight of the perch,then we will compare this to the model that is best overall.


## Perch

```{r}
Fish <- read.csv("Fish.csv")
perch <- filter(Fish, Species == "Perch")
```

```{r}
perch <- select(perch,-Species)
```

### Best Models
```{r}
perchModel <- lm(Weight~., data=perch)
summary(perchModel)
```
```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```


### Best Two regressor model



## Pike


### Best Models

### Best Two regressor model


## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements